#include <stdio.h>

/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

int main(){
	int counter = 0, sum_of_even_numbers = 0, number1 = 0, number2 = 1, result;
	for(counter = 0; counter < 32; counter++){
		result = number1 + number2;
		number1 = number2;
		number2 = result;
		if(result % 2 == 0){
			sum_of_even_numbers = sum_of_even_numbers + result;
		}
	}
	printf("\nSum of even numbers not exceeding 4 million : %d\n",sum_of_even_numbers);
	return 0;
}